#!/usr/bin/env python3
"""
Entry point for live rotation signal generation and notification.
Determines if today is the last trading day of the week, and if the current time
is past the trigger hour, it runs the pipeline and sends a WeChat notification.
"""
from __future__ import annotations

import argparse
import datetime
import requests
import sys

from src.config import (
    ENABLE_WECHAT_PUSH,
    NOTIFY_AFTER_WEEKLY_SIGNAL,
    SERVERCHAN_SENDKEY,
    WEEKLY_SIGNAL_RUN_HOUR,
)
from src.data_loader import is_last_trading_day_of_week
from src.pipeline import main as run_pipeline


def should_run_weekly_signal(now: datetime.datetime, target_date: str | None = None) -> bool:
    """
    Check if we should run the weekly signal.
    Condition: It is the last A-share trading day of the week, and time >= 17:00.
    """
    if target_date:
        print(f"[INFO] Using overridden target date: {target_date}")
        is_last_day = is_last_trading_day_of_week(target_date)
        if not is_last_day:
            print("[INFO] Not the last trading day of the week. Skipping run.")
            return False
        return True
    else:
        date_str = now.strftime("%Y-%m-%d")
        print(f"[INFO] Checking live trading calendar for today: {date_str}")
        is_last_day = is_last_trading_day_of_week(date_str)

        if not is_last_day:
            print("[INFO] Not the last trading day of the week. Skipping run.")
            return False

        print("[INFO] Today is the last trading day of the week.")

        if now.hour < WEEKLY_SIGNAL_RUN_HOUR:
            print(f"[INFO] Current time ({now.strftime('%H:%M')}) is before the trigger hour ({WEEKLY_SIGNAL_RUN_HOUR}:00). Skipping run.")
            return False

    print("[INFO] Trigger condition met \u2192 running weekly signal.")
    return True


def push_serverchan_notification(markdown_content: str, title: str = "ETF 板块轮动策略 - 调仓信号") -> None:
    """Push markdown text to WeChat via ServerChan."""
    if not ENABLE_WECHAT_PUSH:
        print("[INFO] SERVERCHAN_SENDKEY is not set. Skipping WeChat push.")
        return

    url = f"https://sctapi.ftqq.com/{SERVERCHAN_SENDKEY}.send"
    data = {
        "title": title,
        "desp": markdown_content
    }

    try:
        response = requests.post(url, data=data, timeout=10)
        response.raise_for_status()
        print("[INFO] Successfully pushed notification via ServerChan.")
    except Exception as exc:
        print(f"[ERROR] Failed to push ServerChan notification: {exc}")

def get_markdown_lines(latest_date_str: str) -> list[str]:
    import pandas as pd
    from src.config import OUTPUT_DIR

    # Load the latest top 10 targets generated by the pipeline for the test (OOS) period
    targets_file = OUTPUT_DIR / "top10_scored_targets_test.csv"

    md_lines = [
        f"### 📅 调仓信号执行日期: {latest_date_str}",
        "",
        "调仓信号触发逻辑已升级为：每周最后一个 A 股交易日 17:00 后自动运行（已自动规避节假日带来的非周五调仓问题）。",
        "",
        "#### 🏆 最新候选打分 (Top 10)",
        "| 排名 | 代码 | 名称 | 分数 | 候选类型 | RSI |",
        "| :--- | :--- | :--- | :--- | :--- | :--- |"
    ]

    if targets_file.exists():
        df = pd.read_csv(targets_file)
        # Find the rows matching the latest date in the CSV
        if not df.empty:
            max_date = df["date"].max()
            latest_targets = df[df["date"] == max_date].head(10)

            for _, row in latest_targets.iterrows():
                c_type = "硬候选" if row.get("rotation_candidate", False) else ("软候选" if row.get("soft_candidate", False) else "观望")
                md_lines.append(
                    f"| {int(row['rank'])} | {row['symbol']} | {row['name']} | {row['rotation_score']:.2f} | {c_type} | {row['rsi14']:.1f} |"
                )
    else:
        md_lines.append("> ⚠️ 警告：未找到最新的目标打分文件。")

    md_lines.extend([
        "",
        "#### 📊 详细策略指标",
        "请前往服务器或本地终端查看 `ETF_Result` 目录下的详细权益曲线和持仓权重变化文件 (`next_trade_holdings_*.csv`)。"
    ])
    return md_lines

def main():
    parser = argparse.ArgumentParser(description="Run ETF Rotation Strategy Weekly Signal")
    parser.add_argument("--date", type=str, help="Override date (YYYY-MM-DD) for backtesting/debugging")
    parser.add_argument("--force-run", action="store_true", help="Force run ignoring time/calendar conditions")
    args = parser.parse_args()

    now = datetime.datetime.now()

    # Check trigger conditions
    if not args.force_run:
        if not should_run_weekly_signal(now, target_date=args.date):
            sys.exit(0)
    else:
        print("[INFO] Force run flag detected. Bypassing calendar and time checks.")

    # 1. Execute the strategy pipeline
    # The pipeline writes artifacts to ETF_Result directory, and returns the top targets and equity curves.
    try:
        results = run_pipeline()
    except Exception as exc:
        print(f"[ERROR] Pipeline execution failed: {exc}")
        sys.exit(1)

    # 2. Notification Phase
    if NOTIFY_AFTER_WEEKLY_SIGNAL:
        print("\n[INFO] Preparing notification message...")
        latest_date_str = args.date if args.date else now.strftime("%Y-%m-%d")
        md_lines = get_markdown_lines(latest_date_str)
        markdown_message = "\n".join(md_lines)
        print("\n======== MESSAGE PREVIEW ========")
        print(markdown_message)
        print("=================================\n")
        push_serverchan_notification(markdown_message)

if __name__ == "__main__":
    main()